name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.7.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: install
      working-directory: ./frontend
      run: npm install
      
    - name: test
      working-directory: ./frontend
      run: npm test -- --watchAll=false
      env:
        CI: true
      
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest  
    steps:    
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
